export const throwAsyncError = fn => async () => {};
